name: Build and deploy to test environment
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  setup:
    name: Setup
    uses: equinor/data-marketplace-indexer/.github/workflows/_setup.yml@main
    with:
      cache-key: ${{ github.sha }}
    secrets: inherit
  deploy:
    uses: equinor/data-marketplace-indexer/.github/workflows/_deploy.yml@main
    needs: setup
    with:
      environment: test
      cache-key: ${{ github.sha }}
    secrets: inherit
