name: Build and deploy to test environment
on:
  workflow_dispatch:
    bicep-branch:
      required: false
      type: string
      default: main

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  check-code:
    uses: equinor/data-marketplace-indexer/.github/workflows/check-code.yml@main
  deploy:
    uses: equinor/data-marketplace-indexer/.github/workflows/_deploy.yml@main
    with:
      environment: prod
