name: Check code
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '**.{j,t}s'
  pull_request:
    branches: [main]
    paths:
      - '**.{j,t}s'

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  setup:
    name: Setup
    uses: equinor/data-marketplace-indexer/.github/workflows/_setup.yml@main
    with:
      cache-key: ${{ github.sha }}
    secrets: inherit

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Get files
        id: get-files
        uses: actions/cache@v3
        with:
          path: |
            ./*
            .npm
          key: ${{ github.sha }}
      - name: Run linter
        id: lint
        run: npm run lint
      - name: Log errors to Slack 📄
        id: slack-err-log
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()

  test:
    name: Test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Get files
        id: get-files
        uses: actions/cache@v3
        with:
          path: |
            ./*
            .npm
          key: ${{ github.sha }}
      - name: Run tests
        id: test
        run: npm test -- --passWithNoTests
      - name: Log errors to Slack 📄
        id: slack-err-log
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()
